<?php

namespace WinLocalInc\Chjs\Database\Seeders;

use Illuminate\Database\Seeder;
use WinLocalInc\Chjs\Models\Component;
use WinLocalInc\Chjs\Models\ComponentPrice;

class ComponentSeeder extends Seeder
{
    public function run(): void
    {
        Component::insert($this->componentDummyData());
        ComponentPrice::insert($this->componentPriceDummyData());
    }

    private function componentDummyData(): array
    {
        return [
            [
                'component_id' => 2371111,
                'component_handle' => 'sharecard_zero',
                'component_name' => 'ShareCard™',
                'component_unit' => 'component',
                'component_type' => 'quantity_based_component',
                'component_is_active' => 1,
            ],
            [
                'component_id' => 2371112,
                'component_handle' => 'sharecard_pro_zero',
                'component_name' => 'ShareCard™ Pro zero',
                'component_unit' => 'component',
                'component_type' => 'quantity_based_component',
                'component_is_active' => 1,
            ],
            [
                'component_id' => 2371114,
                'component_handle' => 'sharecard_pro_month',
                'component_name' => 'ShareCard™ Pro month',
                'component_unit' => 'component',
                'component_type' => 'quantity_based_component',
                'component_is_active' => 1,
            ],
            [
                'component_id' => 2371115,
                'component_handle' => 'sharecard_pro_year',
                'component_name' => 'ShareCard™ Pro year',
                'component_unit' => 'component',
                'component_type' => 'quantity_based_component',
                'component_is_active' => 1,
            ],
            [
                'component_id' => 2371668,
                'component_handle' => 'sharecard_pro_biannual',
                'component_name' => 'ShareCard™ Pro biannual',
                'component_unit' => 'component',
                'component_type' => 'quantity_based_component',
                'component_is_active' => 1,
            ],
            [
                'component_id' => 2371669,
                'component_handle' => 'company_month',
                'component_name' => 'Company month',
                'component_unit' => 'component',
                'component_type' => 'quantity_based_component',
                'component_is_active' => 1,
            ],
            [
                'component_id' => 2371670,
                'component_handle' => 'company_biannual',
                'component_name' => 'Company biannual',
                'component_unit' => 'component',
                'component_type' => 'quantity_based_component',
                'component_is_active' => 1,
            ],
            [
                'component_id' => 2371671,
                'component_handle' => 'company_year',
                'component_name' => 'Company year',
                'component_unit' => 'component',
                'component_type' => 'quantity_based_component',
                'component_is_active' => 1,
            ],
            [
                'component_id' => 2371672,
                'component_handle' => 'company_zero',
                'component_name' => 'Company zero',
                'component_unit' => 'component',
                'component_type' => 'quantity_based_component',
                'component_is_active' => 1,
            ],
            [
                'component_id' => 2371674,
                'component_handle' => 'brokerage_zero',
                'component_name' => 'Brokerage zero',
                'component_unit' => 'component',
                'component_type' => 'quantity_based_component',
                'component_is_active' => 1,
            ],
            [
                'component_id' => 2371675,
                'component_handle' => 'brokerage_month',
                'component_name' => 'Brokerage month',
                'component_unit' => 'component',
                'component_type' => 'quantity_based_component',
                'component_is_active' => 1,
            ],
            [
                'component_id' => 2371676,
                'component_handle' => 'brokerage_biannual',
                'component_name' => 'Brokerage biannual',
                'component_unit' => 'component',
                'component_type' => 'quantity_based_component',
                'component_is_active' => 1,
            ],
            [
                'component_id' => 2371677,
                'component_handle' => 'brokerage_year',
                'component_name' => 'Brokerage year',
                'component_unit' => 'component',
                'component_type' => 'quantity_based_component',
                'component_is_active' => 1,
            ],
            [
                'component_id' => 2371678,
                'component_handle' => 'kits',
                'component_name' => 'Kits',
                'component_unit' => 'kit',
                'component_type' => 'quantity_based_component',
                'component_is_active' => 1,
            ],
            [
                'component_id' => 2371679,
                'component_handle' => 'cards',
                'component_name' => 'Cards',
                'component_unit' => 'Card',
                'component_type' => 'quantity_based_component',
                'component_is_active' => 1,
            ],
            [
                'component_id' => 2371680,
                'component_handle' => 'tags',
                'component_name' => 'Tags',
                'component_unit' => 'Tag',
                'component_type' => 'quantity_based_component',
                'component_is_active' => 1,
            ],
            [
                'component_id' => 2371682,
                'component_handle' => 'ad_credit',
                'component_name' => 'Ad Credit',
                'component_unit' => 'credit',
                'component_type' => 'quantity_based_component',
                'component_is_active' => 1,
            ],
            [
                'component_id' => 2371683,
                'component_handle' => 'ad_credit_one_time',
                'component_name' => 'Ad Credit One Time',
                'component_unit' => 'credit',
                'component_type' => 'quantity_based_component',
                'component_is_active' => 1,
            ],
            [
                'component_id' => 2371685,
                'component_handle' => 'manage_service',
                'component_name' => 'Manage Service',
                'component_unit' => 'component',
                'component_type' => 'quantity_based_component',
                'component_is_active' => 1,
            ],
            [
                'component_id' => 2371686,
                'component_handle' => 'manage_service_one_time',
                'component_name' => 'Manage Service One Time',
                'component_unit' => 'component',
                'component_type' => 'quantity_based_component',
                'component_is_active' => 1,
            ],
            [
                'component_id' => 2371687,
                'component_handle' => 'setup_fee',
                'component_name' => 'Setup Fee',
                'component_unit' => 'component',
                'component_type' => 'quantity_based_component',
                'component_is_active' => 1,
            ],
        ];

    }

    private function componentPriceDummyData(): array
    {
        return [
            [
                'component_price_id' => 3127342,
                'component_id' => 2371111,
                'component_handle' => 'sharecard_zero',
                'component_price_handle' => 'sharecard_zero',
                'component_price_name' => 'Sharecard zero',
                'component_price_scheme' => 'per_unit',
                'component_price_type' => 'default',
                'component_price_in_cents' => 0,
                'component_price_is_active' => 1,
                'created_at' => '2023-10-12 09:32:19',
                'updated_at' => '2023-10-13 14:20:52',
            ],
            [
                'component_price_id' => 3127343,
                'component_id' => 2371112,
                'component_handle' => 'sharecard_pro_zero',
                'component_price_handle' => 'sharecard_pro_zero',
                'component_price_name' => 'zero',
                'component_price_scheme' => 'per_unit',
                'component_price_type' => 'default',
                'component_price_in_cents' => 0,
                'component_price_is_active' => 1,
                'created_at' => '2023-10-12 09:35:39',
                'updated_at' => '2023-10-12 09:36:07',
            ],
            [
                'component_price_id' => 3127345,
                'component_id' => 2371114,
                'component_handle' => 'sharecard_pro_month',
                'component_price_handle' => 'sharecard_pro_month',
                'component_price_name' => 'month',
                'component_price_scheme' => 'per_unit',
                'component_price_type' => 'default',
                'component_price_in_cents' => 1000,
                'component_price_is_active' => 1,
                'created_at' => '2023-10-12 09:37:59',
                'updated_at' => '2023-10-12 09:38:14',
            ],
            [
                'component_price_id' => 3127346,
                'component_id' => 2371115,
                'component_handle' => 'sharecard_pro_year',
                'component_price_handle' => 'sharecard_pro_year',
                'component_price_name' => 'year',
                'component_price_scheme' => 'per_unit',
                'component_price_type' => 'default',
                'component_price_in_cents' => 9600,
                'component_price_is_active' => 1,
                'created_at' => '2023-10-12 09:39:29',
                'updated_at' => '2023-10-12 09:39:39',
            ],
            [
                'component_price_id' => 3130152,
                'component_id' => 2371668,
                'component_handle' => 'sharecard_pro_biannual',
                'component_price_handle' => 'sharecard_pro_biannual',
                'component_price_name' => 'Sharecard pro biannual',
                'component_price_scheme' => 'per_unit',
                'component_price_type' => 'default',
                'component_price_in_cents' => 5400,
                'component_price_is_active' => 1,
                'created_at' => '2023-10-13 11:54:18',
                'updated_at' => '2023-10-13 12:26:18',
            ],
            [
                'component_price_id' => 3130153,
                'component_id' => 2371669,
                'component_handle' => 'company_month',
                'component_price_handle' => 'company_month',
                'component_price_name' => 'Company month',
                'component_price_scheme' => 'per_unit',
                'component_price_type' => 'default',
                'component_price_in_cents' => 10000,
                'component_price_is_active' => 1,
                'created_at' => '2023-10-13 11:58:26',
                'updated_at' => '2023-10-13 12:30:39',
            ],
            [
                'component_price_id' => 3130154,
                'component_id' => 2371670,
                'component_handle' => 'company_biannual',
                'component_price_handle' => 'company_biannual',
                'component_price_name' => 'Company biannual',
                'component_price_scheme' => 'per_unit',
                'component_price_type' => 'default',
                'component_price_in_cents' => 54000,
                'component_price_is_active' => 1,
                'created_at' => '2023-10-13 11:59:22',
                'updated_at' => '2023-10-13 12:30:12',
            ],
            [
                'component_price_id' => 3130159,
                'component_id' => 2371671,
                'component_handle' => 'company_year',
                'component_price_handle' => 'company_year',
                'component_price_name' => 'Company year',
                'component_price_scheme' => 'per_unit',
                'component_price_type' => 'default',
                'component_price_in_cents' => 96000,
                'component_price_is_active' => 1,
                'created_at' => '2023-10-13 12:00:00',
                'updated_at' => '2023-10-13 12:30:57',
            ],
            [
                'component_price_id' => 3130165,
                'component_id' => 2371672,
                'component_handle' => 'company_zero',
                'component_price_handle' => 'company_zero',
                'component_price_name' => 'Company zero',
                'component_price_scheme' => 'per_unit',
                'component_price_type' => 'default',
                'component_price_in_cents' => 0,
                'component_price_is_active' => 1,
                'created_at' => '2023-10-13 12:01:19',
                'updated_at' => '2023-10-13 12:31:14',
            ],
            [
                'component_price_id' => 3130166,
                'component_id' => 2371674,
                'component_handle' => 'brokerage_zero',
                'component_price_handle' => 'brokerage_zero',
                'component_price_name' => 'Brokerage zero',
                'component_price_scheme' => 'per_unit',
                'component_price_type' => 'default',
                'component_price_in_cents' => 0,
                'component_price_is_active' => 1,
                'created_at' => '2023-10-13 12:02:19',
                'updated_at' => '2023-10-13 12:29:50',
            ],
            [
                'component_price_id' => 3130169,
                'component_id' => 2371675,
                'component_handle' => 'brokerage_month',
                'component_price_handle' => 'brokerage_month',
                'component_price_name' => 'Brokerage month',
                'component_price_scheme' => 'per_unit',
                'component_price_type' => 'default',
                'component_price_in_cents' => 0,
                'component_price_is_active' => 1,
                'created_at' => '2023-10-13 12:07:05',
                'updated_at' => '2023-10-13 12:29:14',
            ],
            [
                'component_price_id' => 3130170,
                'component_id' => 2371676,
                'component_handle' => 'brokerage_biannual',
                'component_price_handle' => 'brokerage_biannual',
                'component_price_name' => 'Brokerage biannual',
                'component_price_scheme' => 'per_unit',
                'component_price_type' => 'default',
                'component_price_in_cents' => 0,
                'component_price_is_active' => 1,
                'created_at' => '2023-10-13 12:07:33',
                'updated_at' => '2023-10-13 12:28:41',
            ],
            [
                'component_price_id' => 3130171,
                'component_id' => 2371677,
                'component_handle' => 'brokerage_year',
                'component_price_handle' => 'brokerage_year',
                'component_price_name' => 'brokerage_year',
                'component_price_scheme' => 'per_unit',
                'component_price_type' => 'default',
                'component_price_in_cents' => 0,
                'component_price_is_active' => 1,
                'created_at' => '2023-10-13 12:07:59',
                'updated_at' => '2023-10-13 12:09:20',
            ],
            [
                'component_price_id' => 3130179,
                'component_id' => 2371678,
                'component_handle' => 'kits',
                'component_price_handle' => 'kits',
                'component_price_name' => 'kits',
                'component_price_scheme' => 'per_unit',
                'component_price_type' => 'default',
                'component_price_in_cents' => 100,
                'component_price_is_active' => 1,
                'created_at' => '2023-10-13 12:10:41',
                'updated_at' => '2023-10-13 12:11:06',
            ],
            [
                'component_price_id' => 3130180,
                'component_id' => 2371679,
                'component_handle' => 'cards',
                'component_price_handle' => 'cards',
                'component_price_name' => 'Cards',
                'component_price_scheme' => 'per_unit',
                'component_price_type' => 'default',
                'component_price_in_cents' => 100,
                'component_price_is_active' => 1,
                'created_at' => '2023-10-13 12:11:48',
                'updated_at' => '2023-10-13 12:12:06',
            ],
            [
                'component_price_id' => 3130181,
                'component_id' => 2371680,
                'component_handle' => 'tags',
                'component_price_handle' => 'tags',
                'component_price_name' => 'Tags',
                'component_price_scheme' => 'per_unit',
                'component_price_type' => 'default',
                'component_price_in_cents' => 100,
                'component_price_is_active' => 1,
                'created_at' => '2023-10-13 12:13:07',
                'updated_at' => '2023-10-13 12:13:18',
            ],
            [
                'component_price_id' => 3130186,
                'component_id' => 2371682,
                'component_handle' => 'ad_credit',
                'component_price_handle' => 'ad_credit',
                'component_price_name' => 'Ad credit',
                'component_price_scheme' => 'per_unit',
                'component_price_type' => 'default',
                'component_price_in_cents' => 100,
                'component_price_is_active' => 1,
                'created_at' => '2023-10-13 12:15:22',
                'updated_at' => '2023-10-13 12:15:42',
            ],
            [
                'component_price_id' => 3130187,
                'component_id' => 2371683,
                'component_handle' => 'ad_credit_one_time',
                'component_price_handle' => 'ad_credit_one_time',
                'component_price_name' => 'Ad credit one time',
                'component_price_scheme' => 'per_unit',
                'component_price_type' => 'default',
                'component_price_in_cents' => 100,
                'component_price_is_active' => 1,
                'created_at' => '2023-10-13 12:16:33',
                'updated_at' => '2023-10-13 12:16:51',
            ],
            [
                'component_price_id' => 3130200,
                'component_id' => 2371685,
                'component_handle' => 'manage_service',
                'component_price_handle' => 'manage_service',
                'component_price_name' => 'Manage service',
                'component_price_scheme' => 'per_unit',
                'component_price_type' => 'default',
                'component_price_in_cents' => 100,
                'component_price_is_active' => 1,
                'created_at' => '2023-10-13 12:22:54',
                'updated_at' => '2023-10-13 12:23:05',
            ],
            [
                'component_price_id' => 3130201,
                'component_id' => 2371686,
                'component_handle' => 'manage_service_one_time',
                'component_price_handle' => 'manage-service-one-time',
                'component_price_name' => 'Manage service one time',
                'component_price_scheme' => 'per_unit',
                'component_price_type' => 'default',
                'component_price_in_cents' => 100,
                'component_price_is_active' => 1,
                'created_at' => '2023-10-13 12:23:35',
                'updated_at' => '2023-10-13 12:23:48',
            ],
            [
                'component_price_id' => 3130202,
                'component_id' => 2371687,
                'component_handle' => 'setup_fee',
                'component_price_handle' => 'setup_fee',
                'component_price_name' => 'Setup fee',
                'component_price_scheme' => 'per_unit',
                'component_price_type' => 'default',
                'component_price_in_cents' => 100,
                'component_price_is_active' => 1,
                'created_at' => '2023-10-13 12:24:20',
                'updated_at' => '2023-10-13 12:24:33',
            ],
        ];

    }
}
